### ISSUE TITLE
Create Backend API to Serve Health Statuses of Deployed services in a proj/venue

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#381]
This is an API that the UI can query to get the health statuses.

Backed API is responsible for reading JSON health status file stored in S3 bucket, and parses file, and returns a JSON response that indicates the health statuses of the services.  The first consumer of this information will be a UI/UX web page displaying the statuses.

This API will:
1) Be implemented in the existing Go backend code/API area of the management console (https://github.com/unity-sds/unity-management-console)
2) Will be fronted by an API Gateway entry point that looks like: `https://unity.com/project/venue/health`

Acceptance Criteria:
- [x] Ticket for implementing lambda is complete : https://github.com/unity-sds/unity-cs/issues/367
- [x] Ticket for S3 bucket creation is complete : https://github.com/unity-sds/unity-cs/issues/380
- [x] Ticket for S3 SSM parameter creation is complete : https://github.com/unity-sds/unity-cs/issues/370
- [x] API Gateway setup gets created by the run.sh (deployment of a venue) chain of events
- [x] MC API can be successfully queried via the API GW URL, and returns health Check JSON that's stored in the S3 bucket.
- [x] The UI/UX "UI Navbar" component is happily able to request this data via the MC API

**Comment by GodwinShen** [comment]
@jdrodjpl and @galenatjpl ping for status update

**Comment by jdrodjpl** [comment]
Making good progress, have the MC backend querying for the parameter and getting the values, just working now on the JSON output. On track for completion early next week.

**Comment by GodwinShen** [comment]
@jdrodjpl ping for status, is this still on track for early this week?

**Comment by jdrodjpl** [comment]
So far, the only hitch (which I didn't realize) is that we don't yet have health check data being populated to the bucket. I'm working with @hargitayjpl to get the correct bucket created and populated with data so I can ensure that the end-to-end process is working.

**Comment by GodwinShen** [comment]
@jdrodjpl ping for status.

**Comment by jdrodjpl** [comment]
I think we are dealing with a pretty serious issue that's keeping the MC from even booting up right now.

Otherwise, I have the code done and tested to create the bucket and parse the health check statuses and pass them along to the API Gateway, and I have the code done to create the Shared Services API Gateway but I'm unable to test it while we figure out what borked the MC (seems to be something in the stack startup that's not consistently populating the SSM param for the health check bucket location, right @hargitayjpl ?

**Comment by galenatjpl** [comment]
Hi @jdrodjpl, I think we said we would have an internal team demo of this (where we are at) tomorrow (6/18), correct?

**Comment by jdrodjpl** [comment]
I was held up trying to figure out the API Gateway stuff but after some guidance from @mike-gangl I'm ready to go on my end. Probably just need to unify my work with what @hargitayjpl has been doing.

**Comment by galenatjpl** [comment]
@mike-gangl this API work has been completed in 24.2, and we are marking this as done.  The API Gateway might need to be tweaked a bit in the future, and we will create a new ticket if necessary for this.  @hargitayjpl will do final testing, including hitting this API in https://github.com/unity-sds/unity-cs/issues/423.
A testing URL was handing off to the UI/UX Team last week, that exercises the returning of the JSON content.
